/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2023-01-25 10:53:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.highland;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import org.apache.log4j.Logger;
import java.sql.*;

public final class search_005fproduction_005fcalc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


 static Logger logger = Logger.getLogger("wet_production_calc.jsp"); //log4j를 위해 

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

boolean connection = false;
Connection conn = null;
String driver = "oracle.jdbc.driver.OracleDriver";
String url = "jdbc:oracle:thin:@192.168.0.5:1521:highland"; //real
//String url = "jdbc:oracle:thin:@192.168.0.7:1523:highland"; //test
//String url = "jdbc:oracle:thin:@192.168.0.14:1521:highland"; //test
request.setCharacterEncoding("euc-kr");

String qry_where = request.getParameter("data");
logger.info("==================================");
logger.info("=========search_shipment==========");
logger.info("==================================");
System.out.println(qry_where);
try {
	Class.forName(driver); 	
	conn = DriverManager.getConnection(url, "inno", "leesgp6000"); //real
	//conn = DriverManager.getConnection(url, "HIGHLAND", "H0124"); //test
	connection = true;
	//System.out.println("DB ?�결 ?�공");
} catch (Exception e) {
	connection = false;
	System.out.println("DB 연결 실패");
	out.println(e.getMessage().toString());
	e.printStackTrace();
} 
 //SQL 
  Statement stmt = conn.createStatement();
 
  String quertystring = "SELECT " 
			+ " C.WEIGHT_FROM"
			+ ",C.WEIGHT_TO"
			+ ",C.ZEROPOINT"
			+ ",C.BASEUNIT"
			+ " FROM B_SUPPLIER_ITEM a"
			+ ",S_BARCODE_INFO c"
			+ " WHERE    a.SUPPLIER_ITEM_ID = c.SUPPLIER_ITEM_ID "
			+ " AND A.STATUS = 'Y'"
			+ " AND ROWNUM = 1"
			+ qry_where;
			
  ResultSet rs = stmt.executeQuery(quertystring);
  
  System.out.println(quertystring);
  logger.info("##serch_shipment query: " + quertystring);
  
  ResultSetMetaData rsmd = rs.getMetaData();
	int columnCnt = rsmd.getColumnCount();

  while(rs.next())
  {
//   out.println(rs.getString("WEIGHT_FROM") + "::" + rs.getString("WEIGHT_TO") + ";;");
     out.println(rs.getString("WEIGHT_FROM") + "::" + rs.getString("WEIGHT_TO") + "::" + rs.getString("ZEROPOINT") + "::" + rs.getString("BASEUNIT"));
//   out.println(rs.getString("DE_CLIENT(IH.CLIENT_CODE)") + "::" + rs.getString("DE_ITEM(ITEM_CODE)") + ";;");
//   out.println(rs.getString(rsmd.getColumnName(1)));
  }
	try{
	  if(rs != null) 
		  rs.close();
	  if(stmt != null) 
		  stmt.close();
	  if(conn != null) 
		  conn.close();
	 }catch(SQLException se){
	
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
