/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2025-01-09 12:13:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.inno;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.*;
import java.util.Date;
import java.text.*;
import java.lang.*;
import java.util.logging.Logger;

public final class insert_005fgoods_005fwet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


 static Logger logger = Logger.getLogger("insert_goods_wet.jsp");

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

boolean connection = false;
Connection conn = null;
String driver = "oracle.jdbc.driver.OracleDriver";
 String url = "jdbc:oracle:thin:@192.168.0.5:1521:highland";
// String url = "jdbc:oracle:thin:@192.168.0.7:1523:highland";

request.setCharacterEncoding("euc-kr");
String data = request.getParameter("data");
String dbid = request.getParameter("dbid");

try {
	Class.forName(driver); 
	conn = DriverManager.getConnection(url, dbid, "leesgp6000");
	connection = true;
} catch (Exception e) {
	connection = false;
	out.println(e.getMessage().toString());
	e.printStackTrace();
} 
try {
	String[] splitData = data.split("::");
	
  logger.info("============================================");
  logger.info("=========insert_goods_wet start=============");
  logger.info("============================================");
  logger.info("##insert_goods_wet all parameter :" + data);	

  SimpleDateFormat dateformat = new SimpleDateFormat("yyyyMMdd");
  SimpleDateFormat timeformat = new SimpleDateFormat("HHmmss");

  long now = System.currentTimeMillis();
  Date datetime = new Date(now);
  String dateStr = dateformat.format(datetime);
  String timeStr = timeformat.format(datetime);

 //SQL 
  String qry = "INSERT INTO W_GOODS_WET(GOODS_WET_ID"
		+ ", GI_D_ID"
		+ ", WEIGHT"
		+ ", WEIGHT_UNIT"
		+ ", PACKER_PRODUCT_CODE"
		+ ", BARCODE"
		+ ", PACKER_CLIENT_CODE"
		+ ", MAKINGDATE"
		+ ", BOXSERIAL"
		+ ", BOX_CNT"
		+ ", REG_ID"
		+ ", REG_DATE"
		+ ", REG_TIME)"
		+ " VALUES "
		+ "(W_GOODS_WET_SEQ.NEXTVAL,?,?,?,?,?,?,?,?,?,?,?,?)";
  PreparedStatement pstmt = conn.prepareStatement(qry);    


  pstmt.setInt(1, Integer.parseInt(splitData[0]));
  pstmt.setDouble(2, (Double.parseDouble(splitData[1]) * 100) / 100.0);
  pstmt.setString(3, splitData[2]);
  pstmt.setString(4, splitData[3]);
  pstmt.setString(5, splitData[4]);
  pstmt.setString(6, splitData[5]);
  pstmt.setString(7, splitData[6]);
  pstmt.setString(8, splitData[7]);
  pstmt.setInt(9, Integer.parseInt(splitData[8]));
  pstmt.setString(10, splitData[9]);
  pstmt.setString(11, dateStr);
  pstmt.setString(12, timeStr);

  
/*
  pstmt.setInt(1, 1234567);
//  pstmt.setDouble(2, ((Double.parseDouble("12.30")) * 100) / 100);
//  pstmt.setDouble(2, 123.30);
  pstmt.setString(2, "test");
  pstmt.setString(3, "test");
  pstmt.setString(4, "test");
  pstmt.setString(5, "test");
  pstmt.setInt(6, 1);
  pstmt.setString(7, "test");
  pstmt.setString(8, dateStr);
  pstmt.setString(9, timeStr);
*/
  
  logger.info("##insert_goods_wet query start, query :"+ qry);	
  pstmt.executeUpdate();
/*
	String update_qry = "UPDATE W_GOODS_ID SET "
			+ "GI_QTY = GI_QTY +  ? "
			+ ", PACKING_QTY = PACKING_QTY + 1 "
			+ ", MOD_ID = ? "
			+ ", MOD_DATE = ? "
			+ ", MOD_TIME = ? "
			+ "WHERE GI_D_ID = ? AND ITEM_CODE = ? AND BRAND_CODE = ?"; 
	pstmt = conn.prepareStatement(update_qry);  

	pstmt.setDouble(1, (Double.parseDouble(splitData[1]) * 100) / 100.0);
	pstmt.setString(2, splitData[9]);
	pstmt.setString(3, dateStr);
	pstmt.setString(4, timeStr);
	pstmt.setInt(5, Integer.parseInt(splitData[0]));
	pstmt.setString(6, splitData[10]);		// ITEM_CODE
	pstmt.setString(7, splitData[11]);		// BRAND_CODE

	pstmt.executeUpdate();
*/
	/* System.out.println("============================");
	System.out.println("========GI_D_ID=======" + splitData[0]);
	System.out.println("========WEIGHT========" + splitData[1]);
	System.out.println("========DATE==========" + dateStr + timeStr);
	System.out.println("========REG_ID========" + splitData[9]);
	System.out.println("============================"); */ //logger 추가 후 System.out.println 주석처리, 2019.01.28 park.sj

  conn.commit();
  
  logger.info("##insert_goods_wet parameter : ======INSERT_GOODS_WET PARAMS=====");
  logger.info("##insert_goods_wet parameter : ========GI_D_ID===================" + splitData[0]);
  logger.info("##insert_goods_wet parameter : ========WEIGHT====================" + splitData[1]);
  logger.info("##insert_goods_wet parameter : ========DATE======================" + dateStr + timeStr);
  logger.info("##insert_goods_wet parameter : ========REG_ID====================" + splitData[9]);
  logger.info("##insert_goods_wet parameter : ==================================");
	
  if(pstmt != null) 
	  pstmt.close();
  if(conn != null) 
	  conn.close();
  out.println("s");  
} catch (Exception ex) {
		out.println("f");
		out.println(ex.getMessage());
		ex.printStackTrace();
		logger.info("=============insert_goods_wet exception============== message :" + ex.getMessage().toString());
		conn.rollback();
		conn.close();
}
	
  

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
