/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2024-01-15 04:11:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.inno;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import org.apache.log4j.Logger;

public final class search_005fproduction_005fnonfixed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


 static Logger logger = Logger.getLogger("search_shipment.jsp");

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

boolean connection = false;
Connection conn = null;
String driver = "oracle.jdbc.driver.OracleDriver";
 String url = "jdbc:oracle:thin:@192.168.0.5:1521:highland";
//String url = "jdbc:oracle:thin:@192.168.0.7:1523:highland";
//String url = "jdbc:oracle:thin:@192.168.0.215:1621:highland";
request.setCharacterEncoding("euc-kr");

String qry_where = request.getParameter("data");
/* System.out.println("==================================");
System.out.println("=========search_shipment==========");
System.out.println("==================================");
System.out.println(qry_where); */

logger.info("====================================");
logger.info("=========search_shipment============");
logger.info("====================================");
logger.info("##search_shipment all parameter :" + qry_where);

try {
	Class.forName(driver); 	
	conn = DriverManager.getConnection(url, "inno", "leesgp6000");
	//conn = DriverManager.getConnection(url, "h1020", "pwdh1020");
	connection = true;
	System.out.println("INNO DB 연결 성공");
} catch (Exception e) {
	connection = false;
	System.out.println("INNO DB 연결 실패");
	out.println(e.getMessage().toString());
	e.printStackTrace();
} 
 //SQL 
  Statement stmt = conn.createStatement();
  String quertystring = "SELECT " 
								+ "GI_H_ID"
								+ ", GI_D_ID"
								+ ", EOI_ID"
								+ ", ITEM_CODE"
								+ ", ITEM_NAME"
								+ ", EMARTITEM_CODE"
								+ ", EMARTITEM"
								+ ", GI_REQ_PKG"
								+ ", GI_REQ_QTY"
								+ ", AMOUNT"
								+ ", GOODS_R_ID"
								+ ", GR_REF_NO"
								+ ", GI_REQ_DATE"
								+ ", BL_NO"
								+ ", BRAND_CODE"
								+ ", BRANDNAME"
								+ ", CLIENT_CODE"
								+ ", CLIENTNAME"
								+ ", CENTERNAME"
								+ ", ITEM_SPEC"
								+ ", CT_CODE"
								+ ", IMPORT_ID_NO"
								+ ", PACKER_CODE"
								+ ", PACKERNAME"
								+ ", PACKER_PRODUCT_CODE"
								+ ", BARCODE_TYPE"
								+ ", ITEM_TYPE"
								+ ", PACKWEIGHT"
								+ ", BARCODEGOODS"
								+ ", STORE_IN_DATE"
								+ ", EMARTLOGIS_CODE"
								+ ", EMARTLOGIS_NAME"
								+ ", WH_AREA"
								+ ", USE_NAME"
								+ ", USE_CODE"
								+ ", CT_NAME"
								+ ", STORE_CODE"
								+ " FROM VW_PDA_WID_LIST_NONFIXED"
								+ qry_where
								+ " ORDER BY EOI_ID ASC";
  
  ResultSet rs = stmt.executeQuery(quertystring);
  
  /* System.out.println(quertystring); */
  logger.info("##search_shipment query :" + quertystring);
  
  ResultSetMetaData rsmd = rs.getMetaData();
	int columnCnt = rsmd.getColumnCount(); //컬럼????

  while(rs.next())
  {
   out.println(rs.getString("GI_H_ID") + "::" + rs.getString("GI_D_ID") + "::" + rs.getString("EOI_ID") + "::" + rs.getString("ITEM_CODE") + "::"
			+ rs.getString("ITEM_NAME") + "::" + rs.getString("EMARTITEM_CODE") + "::" + rs.getString("EMARTITEM") + "::" 
			+ rs.getString("GI_REQ_PKG") + "::" + rs.getString("GI_REQ_QTY") + "::" + rs.getString("AMOUNT") + "::" 
			+ rs.getString("GOODS_R_ID") + "::" + rs.getString("GR_REF_NO") + "::" + rs.getString("GI_REQ_DATE") + "::" + rs.getString("BL_NO") + "::"
			+ rs.getString("BRAND_CODE") + "::" + rs.getString("BRANDNAME") + "::" + rs.getString("CLIENT_CODE") + "::" 
			+ rs.getString("CLIENTNAME") + "::" + rs.getString("CENTERNAME") + "::" + rs.getString("ITEM_SPEC") + "::" 
			+ rs.getString("CT_CODE") + "::" + rs.getString("IMPORT_ID_NO") + "::" + rs.getString("PACKER_CODE") + "::" 
			+ rs.getString("PACKERNAME") + "::" + rs.getString("PACKER_PRODUCT_CODE") + "::" + rs.getString("BARCODE_TYPE") + "::" 
			+ rs.getString("ITEM_TYPE") + "::" + rs.getString("PACKWEIGHT") + "::" + rs.getString("BARCODEGOODS") + "::" + rs.getString("STORE_IN_DATE") + "::"
			//+ rs.getString("EMARTLOGIS_CODE") + "::" + rs.getString("EMARTLOGIS_NAME") + "::" + rs.getString("WH_AREA") + ";;");
			+ rs.getString("EMARTLOGIS_CODE") + "::" + rs.getString("EMARTLOGIS_NAME") + "::" + rs.getString("WH_AREA") + "::" + rs.getString("USE_NAME") + "::" + rs.getString("USE_CODE") + "::" + rs.getString("CT_NAME") + "::" + rs.getString("STORE_CODE")+ ";;");
//   out.println(rs.getString("DE_CLIENT(IH.CLIENT_CODE)") + "::" + rs.getString("DE_ITEM(ITEM_CODE)") + ";;");
//      out.println(rs.getString(rsmd.getColumnName(1)));
  }

	try{
	  if(rs != null) 
		  rs.close();
	  if(stmt != null) 
		  stmt.close();
	  if(conn != null) 
		  conn.close();
	 }catch(SQLException se){
	//	 System.out.println("?�결 객체 ?�기 ?�료");
	}


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
