/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2023-08-01 06:21:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.inno;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.util.*;
import java.util.Date;
import java.text.*;
import java.lang.*;
import org.apache.log4j.Logger;

public final class update_005fshipment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


 static Logger logger = Logger.getLogger("update_shipment.jsp");

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

boolean connection = false;
Connection conn = null;
String driver = "oracle.jdbc.driver.OracleDriver";
 String url = "jdbc:oracle:thin:@192.168.0.5:1521:highland";
//String url = "jdbc:oracle:thin:@192.168.0.7:1523:highland";

/* System.out.println("==================================");
System.out.println("==========update_shipment=========");
System.out.println("=================================="); */

request.setCharacterEncoding("euc-kr");

//String data = "test::test::test::test::KG::1::1::1::1::2";
//String[] arrData = data.split("::");

String dbid = request.getParameter("dbid");
String data = request.getParameter("data");
String[] splitData = data.split("::");

logger.info("====================================");
logger.info("=========update_shipment============");
logger.info("====================================");
logger.info("##update_shipment all parameter :" + data);

SimpleDateFormat dateformat = new SimpleDateFormat("yyyyMMdd");
  SimpleDateFormat timeformat = new SimpleDateFormat("HHmmss");

  long now = System.currentTimeMillis();
  Date datetime = new Date(now);
  String dateStr = dateformat.format(datetime);
  String timeStr = timeformat.format(datetime);

	String gi_d_id				= splitData[0];				// 출하번호
	String item_code				= splitData[1];				// ?�이?�코??
	String brand_code				= splitData[2];				// 브랜?�코??
	String reg_id				= splitData[3];				// ?�용?�ID
try {
	Class.forName(driver); 
	conn = DriverManager.getConnection(url, dbid, "leesgp6000");
	connection = true;
} catch (Exception e) {
	connection = false;
	out.println(e.getMessage().toString());
	e.printStackTrace();
} 

try {

 //SQL
 /*
  String qry = "INSERT INTO S_BARCODE_INFO(BARCODE_INFO_ID, PACKER_CLIENT_CODE, PACKER_PRODUCT_CODE, PACKER_PRD_NAME, BRAND_CODE, BARCODEGOODS, BASEUNIT, ZEROPOINT, PARCKER_PRD_CODE_FROM, PACKER_PRD_CODE_TO, BARCODEGOODS_FROM, BARCODEGOODS_TO, WEIGHT_FROM, WEIGHT_TO, STATUS, REG_ID, REG_DATE, REG_TIME) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
*/  


	String qry = "UPDATE W_GOODS_ID set CHECK_YN='N', MOD_ID = ?, MOD_DATE = ?, MOD_TIME = ? WHERE GI_D_ID=? AND ITEM_CODE=? AND BRAND_CODE=?";

	// ?�로??쿼리
  //String qry = "UPDATE W_GOODS_ID set CHECK_YN='Y', STATUS='20' WHERE GI_D_ID=? AND ITEM_CODE=? AND BRAND_CODE=?";

	// ?�스?��? ?�한 쿼리
  //String qry = "UPDATE W_GOODS_ID set CHECK_YN=? WHERE GI_D_ID=? AND ITEM_CODE=? AND BRAND_CODE=?";

  PreparedStatement pstmt = conn.prepareStatement(qry);    

  pstmt.setString(1, splitData[3]);
  pstmt.setString(2, dateStr);
  pstmt.setString(3, timeStr);
  pstmt.setInt(4, Integer.parseInt(splitData[0]));
  pstmt.setString(5, splitData[1]);
  pstmt.setString(6, splitData[2]);


/*
  pstmt.setDouble(1, Double.parseDouble(gi_qty));
  pstmt.setInt(2, Integer.parseInt(packing_qty));
  pstmt.setString(3, check_yn);
  pstmt.setInt(4, Integer.parseInt(gi_d_id));
  pstmt.setString(5, item_code);
  pstmt.setString(6, brand_code);
*/
  pstmt.executeUpdate();
  conn.commit();

/* System.out.println("==================================");
System.out.println("==========update_shipment2=========");
System.out.println("=================================="); */

	logger.info("##update shipment parameter : ====UPDATE_SHIPMENT PARAMS=====");
	logger.info("##update shipment parameter : ========MOD_ID=================" + splitData[3]);
	logger.info("##update shipment parameter : ========DATE===================" + dateStr + timeStr);
	logger.info("##update shipment parameter : ========GI_D_ID================" + Integer.parseInt(splitData[0]));
	logger.info("##update shipment parameter : ========ITEM_CODE==============" + splitData[1]);
	logger.info("##update shipment parameter : ========BRAND_CODE=============" + splitData[2]);
	logger.info("##update shipment parameter : ===============================");

	if(pstmt != null) 
		pstmt.close();
	if(conn != null) 
		conn.close();
  out.println("s");
} catch (SQLException e) {
		out.println("f");
		out.println(e.getMessage().toString());
		logger.info("=============update shipment sql exception============== message :" + e.getMessage().toString());
		conn.rollback();
		if(conn != null) 
		conn.close();
} catch (Exception ex) {
	out.println(ex.getMessage().toString());
	logger.info("=============update_shipment exception============== message :" + ex.getMessage().toString());
	if(conn != null) 
		conn.close();

} 
	
	

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
